services:
  - type: web
    name: quiz-app
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://pyaman003:vjkdRaysGU3rRoTj@quizapp.kcjc3is.mongodb.net/?retryWrites=true&w=majority&appName=quizapp
      - key: SECRET_KEY
        value: QWESE32143@112W768Y@